# permissions for end users to view metricstraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricstrait-viewer-role
rules:
- apiGroups:
  - standard.oam.dev
  resources:
  - metricstraits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - standard.oam.dev
  resources:
  - metricstraits/status
  verbs:
  - get
