# permissions for end users to edit metricstraits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricstrait-editor-role
rules:
- apiGroups:
  - standard.oam.dev
  resources:
  - metricstraits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - standard.oam.dev
  resources:
  - metricstraits/status
  verbs:
  - get
