apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: upload-kfp
  namespace: vela-system
  annotations:
    definition.oam.dev/description: "upload a Kubeflow pipeline"
spec:
  workload:
    type: autodetects.core.oam.dev
  schematic:
    cue:
      template: |
        parameter: {
          image: string
          buildScript: string
          outputDir: string
          outputName: string
        }
        output: {
          apiVersion: "batch/v1"
          kind: "Job"
          spec: {
            template: {
              spec: {
                initContainers: [{
                  name: "build-pipeline"
                  image: parameter.image
                  command: ["/bin/sh"]
                  args: ["-c", parameter.buildScript]
                  volumeMounts: [{name: "output-dir", mountPath: parameter.outputDir}]
                }]
                containers: [{
                  name: "upload-pipeline"
                  image: "acr.kubevela.net/oamdev/kubeflow-tool"
                  command: ["/usr/bin/bash"]
                  args: ["-c", """
                    curl -F "uploadfile=@\(parameter.outputDir)\(parameter.outputName)" ml-pipeline-ui.kubeflow.svc/apis/v1beta1/pipelines/upload
                  """]
                  volumeMounts: [{name: "output-dir", mountPath: parameter.outputDir}]
                }]
                volumes: [{
                  name: "output-dir"
                  emptyDir: {}
                }]
                restartPolicy: "OnFailure"
              }
            }
            backoffLimit: 4
          }
        }
        
        