apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: config
  namespace: vela-system
spec:
  context:
    readConfig: true
  workflowSpec:
    steps:
      - name: Prepare Prometheus
        type: step-group
        subSteps: 
        - name: get-exist-prometheus
          type: list-config
          properties:
            template: prometheus-server
          outputs:
          - name: prometheus
            valueFrom: "output.configs"
        - name: prometheus-server
          inputs:
          - from: prometheus
            parameterKey: "configs"
          if: "!context.readConfig || (inputs.prometheus[0].name==\"prometheus-vela\")"
          type: addon-operation
          properties:
            addonName: terraform-alibaba
            operation: enable