apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: ingresstraits.core.oam.dev
spec:
  workloadRefPath: spec.workloadRef
  appliesToWorkloads:
    - core.oam.dev/v1alpha2.ContainerizedWorkload
    - deployments.apps
    - statefulsets.apps
  definitionRef:
    name: ingresstraits.core.oam.dev
