apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: sample-application-with-metrics
spec:
  components:
    - componentName: autoscale-application
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: MetricsTrait
            spec:
              scrapeService:
                format: "prometheus"
                portName: 80
                path: "/metrics"
                scheme:  "http"
                enabled: true
    - componentName: metrics-application
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: MetricsTrait
            spec:
              scrapeService:
                targetPort: 8080
                path: "/metrics"
                interval:  "5s"
