apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: sample-application-with-metrics
spec:
  components:
    - componentName: autoscale-application
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: MetricsTrait
            spec:
              metricsendpoint:
                port: 80
                path: "/metrics"
                interval:  "1s"
              selector:
                matchLabels:
                  app: sample-app-svc
    - componentName: metrics-application
      traits:
        - trait:
            apiVersion: standard.oam.dev/v1alpha1
            kind: MetricsTrait
            spec:
              metricsendpoint:
                targetPort: 8080
                path: "/metrics"
                interval:  "5s"
              selector:
                matchLabels:
                  app: metrics-app-svc