apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bookinfo-clusterrole
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  - destinationrules
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bookinfo-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bookinfo-clusterrole
subjects:
  - kind: ServiceAccount
    name: crossplane              # Remember to use the actual ServiceAccount name
    namespace: crossplane-system  # Remember to use the actual ServiceAccount namespace
