name: hello

services:
  express-server:
    type: deployment
    image: zzxwill/flask-web-application:v0.3
    ports: 80
    configRef:
      - name: "sample-db"
        keys:
          - "DB_USER"
          - "DB_HOST"
          - "DB_PASSWORD"
      - name: "sample-oss"
        keys:
          - "BUCKET_NAME"

  sample-db:
    type: aliyun-rds
    name: "poc"
    user: "oam"
    password: "xyzXYZxyz"

  sample-oss:
    type: aliyun-oss
    bucket: "oam-website"
