apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: aliyun-rds
  annotations:
    definition.oam.dev/description: Terraform module for Aliyun RDS object
    type: terraform             # To mark this WorkloadDefinition is Terraform module/manifests
spec:
  definitionRef:
    name: deployments.apps      # "NULL" temporary set to `deployments.apps` to let `vela workloads` work
  extension:
    template: |
      output: {
      	{
      		module: {
      			rds: {
      				source:           "terraform-alicloud-modules/rds/alicloud"
      				engine:           parameter.engine
      				engine_version:   parameter.engine_version
      				instance_type:    parameter.instance_type
      				instance_storage: "20"
      				instance_name:    parameter.name
      				account_name:     parameter.user
      				password:         parameter.password
      			}
      		}
      		output: {
      			db_name: {
      				value: "${module.rds.this_db_instance_name}"
      			}
      			DB_USER: {
      				value: "${module.rds.this_db_database_account}"
      			}
      			db_port: {
      				value: "${module.rds.this_db_instance_port}"
      			}
      			DB_HOST: {
      				value: "${module.rds.this_db_instance_connection_string}"
      			}
      			DB_PASSWORD: {
      				value: "${module.rds.this_db_instance_port}"
      			}
      		}
      	}
      }

      parameter: {
      	engine:         *"MySQL" | string
      	engine_version: *"8.0" | string
      	instance_type: *"rds.mysql.c1.large" | string
      	name:           string
      	user:           string
      	password:       string
      }
