apiVersion: v1
kind: ConfigMap
metadata:
  name: oam-grafana-datasource
  namespace: oam-monitoring
  labels:
    grafana_datasource: "2"
    app: oam-runtime
    chart: prometheus-operator-4.3.1
    release: "oam-runtime"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus-OAM
      type: prometheus
      url: http://prometheus-oam:4848/
      access: proxy
      isDefault: false